security:
  basic:
    enabled: false  # unsecure app endpoints

management:
  security:
    enabled: false  # unsecure actuator endpoints

logging: # <----New sections below
  level:
    io:
      pivotal: INFO

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote